### ISSUE TITLE
[Feature Suggest] Make players died to void/lava can keep their items

### ISSUE THREAD

**Issue by Surgeol** [DiemondPlayer/IDiedMyItemsDidnt#1]
Can you add an option to chose whether spawn a chest(more if a chest isn't enough) to contain player's items when they died to lava/void?
For example, when a player falls into the void, one or two chests will be spawned at the bottom of the current world (If there's not enough space, continue searching upwards until there is room to generate), containing all the player's items.

Really love your mod idea :heart:

**Comment by DiemondPlayer** [comment]
Hello! I do understand why would you want such feature to be added, however, I think that will just make it another gravestone mod, which kind of defeats the purpose of the mod since this is meant to be a less cheaty alternative to graves. From what I understood, you want a kind of mix between regular deaths when everything just flies out and for the mod to spawn chests only when needed like in lava or void. While I do not know any mods that do that mix specifically, I think it would be pretty hard to code such behavior that determined whether the circumstances you died in were "harmful to your items". You can just die by the lava, not in it, and some of your stuff will burn, or it could fall from a mountain on a cactus or, again, lava. I think the best solution for you is to find a graves mod of some kind, even if it spawns the graves every time someone dies. Thanks for the suggestion thought, for now my answer is "no", but I am open to talk if you have more arguments/reasons to add such feature. Thanks for feedback!
