### ISSUE TITLE
[Feature] Configurable despawn timer (multi hour-day long timers)

### ISSUE THREAD

**Issue by zndrmn** [DiemondPlayer/IDiedMyItemsDidnt#2]
It would be great if there was a way to configure how long it takes for things to despawn. I believe that if this were to be installed on a semi-large survival server, items that were never collected would stay there permanently and could (will) cause lag over a long period of time.

**Comment by DiemondPlayer** [comment]
Hello! I might consider adding this in the future, but I am not sure. Also, for what I know, items that are in unloaded chunks do not count their despawn time anyway so there isn't really any additional lag for the server. And for items in loaded chunks, I think they will be collected eventually since the player wants to get their stuff back (usually). Considering that my mod only affects items dropped by player death and none of other ways to drop them, I do not think that should load the server that much. Still, thanks for the suggestion. Again, I am not sure whether I will add such config, but I will consider it. Also, you can check out different plugins/mods that do that cause I believe someone already did somthing like that, just for all of the items, not the death drops exclusively. If you want to add anything else, feel free to do so, otherwise I think we can safely close the thread.

**Comment by zndrmn** [comment]
Yeah I just meant for loaded chunks, I just feel like over a really really long time random items could never be collected and add up. Especially during early game when you don't really worry too much about your items. Oh and sometimes your items can go absolutely flying which could make them really hard to find and recover. Though still it probably wouldn't really cause any noticeable lag for a longg time (years in a singleplayer world), but I still think it could cause problems on some servers if they're big enough or if enough new players join and die a bunch.
I think that's all I have to add, if you feel like it you can close this<sup>tm</sup>.
